model:
  name: "smollm2"
  version: "1.7B"

dataset:
  name: "truthful_qa"
  distortion_percentage: 0.3

distortion:
  type: [[], ["character"], ["sentence"], ["sentence random"], ["phonetic"]]

evaluation:
  file: "evaluations/"

cache_dir:
  path: "/share/garg/Marco/Models"